-- +goose Up
-- +goose StatementBegin
CREATE TABLE TENANT
(
    ID         TEXT      NOT NULL PRIMARY KEY,
    NAME       TEXT      NOT NULL,
    WORKSPACE  TEXT      NOT NULL DEFAULT '',
    TEAM_ID    TEXT      NOT NULL DEFAULT '',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACTIVE     SMALLINT  NOT NULL DEFAULT TRUE
);

CREATE TABLE API_KEY
(
    ID         TEXT      NOT NULL PRIMARY KEY,
    TENANT_ID  TEXT      NOT NULL,
    KEY_HASH   TEXT      NOT NULL UNIQUE,
    KEY_PREFIX TEXT      NOT NULL,
    NAME       TEXT      NOT NULL DEFAULT '',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP,
    ACTIVE     SMALLINT  NOT NULL DEFAULT TRUE,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANT (ID) ON DELETE CASCADE
);
CREATE INDEX API_KEY_TENANT_ID_IDX ON API_KEY (TENANT_ID);

CREATE TABLE CREDENTIAL
(
    ID         TEXT      NOT NULL PRIMARY KEY,
    TENANT_ID  TEXT      NOT NULL UNIQUE,
    TOKEN_ENC  BLOB      NOT NULL,
    COOKIE_ENC BLOB,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANT (ID) ON DELETE CASCADE
);

CREATE TABLE EXPORT_JOB
(
    ID           TEXT      NOT NULL PRIMARY KEY,
    TENANT_ID    TEXT      NOT NULL,
    STATUS       TEXT      NOT NULL DEFAULT 'pending',
    CHANNELS     TEXT      NOT NULL DEFAULT '',
    TRIGGERED_BY TEXT      NOT NULL DEFAULT 'manual',
    ERROR_MSG    TEXT      NOT NULL DEFAULT '',
    OUTPUT_PATH  TEXT      NOT NULL DEFAULT '',
    STARTED_AT   TIMESTAMP,
    FINISHED_AT  TIMESTAMP,
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANT (ID) ON DELETE CASCADE
);
CREATE INDEX EXPORT_JOB_TENANT_ID_IDX ON EXPORT_JOB (TENANT_ID);
CREATE INDEX EXPORT_JOB_STATUS_IDX ON EXPORT_JOB (STATUS);

CREATE TABLE SCHEDULE
(
    ID          TEXT      NOT NULL PRIMARY KEY,
    TENANT_ID   TEXT      NOT NULL UNIQUE,
    ENABLED     SMALLINT  NOT NULL DEFAULT TRUE,
    HOUR_UTC    INTEGER   NOT NULL DEFAULT 2,
    JITTER_MIN  INTEGER   NOT NULL DEFAULT 60,
    LAST_RUN_AT TIMESTAMP,
    NEXT_RUN_AT TIMESTAMP,
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TENANT_ID) REFERENCES TENANT (ID) ON DELETE CASCADE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS SCHEDULE;
DROP TABLE IF EXISTS EXPORT_JOB;
DROP TABLE IF EXISTS CREDENTIAL;
DROP TABLE IF EXISTS API_KEY;
DROP TABLE IF EXISTS TENANT;
-- +goose StatementEnd
